export const TEXT_MAP = {
  en: {
    heading: 'About',
    content: 'My name is Dr. David Partyka, and I created Kepler Stats. Although I was trained for several years as a chemist, and even earned a PhD from a top university and published over 20 papers, I transitioned into web development after the last engineering company I worked for (heavily-focused on chemistry) folded in 2011. I made this career transition for better employment and work-life balance opportunities, and years later, I wholeheartedly believe this was the correct choice.<br /><br />&emsp;I feel that I am in an almost unique position in that I can now use my scientific and analytical skills to develop websites (such as my CSS parsing tool, <a href="https://cssburner.com" target="_blank" rel="noreferrer">CSSBurner</a>) that other people, or even teams, would not be able to cost-efficiently produce because such sites would require multiple personnel with different skill sets. The <a href="https://www.asterank.com/kepler" target="_blank" rel="noreferrer">Kepler Project API</a>, which queries a NASA database of over 2,000 exoplanets and unconfirmed objects of interest, presents one such opportunity. This database admirably attempts to make scientific data available to the public. However, the esoteric nature of the API parameters, appended in a format compatible with Mongo DB, renders nearly impossible actual public access. Kepler Stats is an effort to visualize the statistics of the Kepler Project\'s database and integrate "value-added" filters - as an easy-to-use user interface available in multiple languages - so that anyone with enough curiosity can more fully appreciate the value of the Kepler Project\'s valuable data.'
  },
  es: {
    heading: 'Acerca de',
    content: 'Mi nombre es Dr. David Partyka y creé Kepler Stats. Aunque me formé como químico durante varios años, e incluso obtuve un doctorado de una de las mejores universidades y publiqué más de 20 artículos, hice la transición al desarrollo web después de que la última empresa de ingeniería para la que trabajé (muy centrada en la química) cerró en 2011. Hice esta transición profesional para obtener mejores oportunidades de empleo y equilibrio entre vida personal y laboral, y años después, creo sinceramente que esta fue la elección correcta.<br /><br />&emsp;Siento que estoy en una posición casi única en ese sentido. Ahora puedo utilizar mis habilidades científicas y analíticas para desarrollar sitios web (como mi herramienta de análisis de CSS, <a href="https://cssburner.com" target="_blank" rel="noreferrer">CSSBurner</a>) que otras personas, o incluso equipos, no podrían producir de manera rentable porque dichos sitios requerirían mucho personal con diferentes habilidades. La <a href="https://www.asterank.com/kepler" target="_blank" rel="noreferrer">API del Proyecto Kepler</a>, que consulta una base de datos de la NASA de más de 2.000 exoplanetas y objetos no confirmados de interés, presenta una de esas oportunidades. Esta base de datos intenta admirablemente poner los datos científicos a disposición del público. Sin embargo, la naturaleza esotérica de los parámetros API, añadidos en un formato compatible con Mongo DB, hace que el acceso público real sea casi imposible. Kepler Stats es un esfuerzo por visualizar las estadísticas de la base de datos del Proyecto Kepler e integrar filtros de "valor agregado", como una interfaz de usuario fácil de usar disponible en varios idiomas, para que cualquier persona con suficiente curiosidad pueda apreciar mejor el valor de los valiosos datos del Proyecto Kepler.'
  },
  fr: {
    heading: 'À propos',
    content: 'Je m\'appelle le Dr David Partyka et j\'ai créé Kepler Stats. Bien que j\'aie été formé pendant plusieurs années en tant que chimiste, et que j\'ai même obtenu un doctorat dans une grande université et publié plus de 20 articles, je me suis tourné vers le développement Web après la fermeture de la dernière société d\'ingénierie pour laquelle j\'ai travaillé (fortement axée sur la chimie) en 2011. J\'ai fait cette transition de carrière pour de meilleures opportunités d\'emploi et d\'équilibre travail-vie personnelle, et des années plus tard, je crois de tout cœur que c\'était le bon choix.<br /><br />&emsp;Je sens que je suis dans une position presque unique dans ce domaine. Je peux désormais utiliser mes compétences scientifiques et analytiques pour développer des sites Web (comme mon outil d\'analyse CSS, <a href="https://cssburner.com" target="_blank" rel="noreferrer">CSSBurner</a>) que d\'autres personnes, ou même des équipes, ne seraient pas en mesure de produire de manière rentable car de tels sites nécessiteraient plusieurs personnes possédant des compétences différentes. <a href="https://www.asterank.com/kepler" target="_blank" rel="noreferrer">L\'API du projet Kepler</a>, qui interroge une base de données de la NASA contenant plus de 2 000 exoplanètes et objets non confirmés de intérêt, présente une telle opportunité. Cette base de données tente admirablement de mettre les données scientifiques à la disposition du public. Cependant, la nature ésotérique des paramètres de l\'API, ajoutés dans un format compatible avec Mongo DB, rend l\'accès public réel presque impossible. Kepler Stats est un effort visant à visualiser les statistiques de la base de données du projet Kepler et à intégrer des filtres à valeur ajoutée - sous la forme d\'une interface utilisateur facile à utiliser et disponible en plusieurs langues - afin que toute personne suffisamment curieuse puisse mieux apprécier la valeur des précieuses données du projet Kepler.'
  },
  it: {
    heading: 'Di',
    content: 'Mi chiamo Dr. David Partyka e ho creato Kepler Stats. Sebbene abbia studiato per diversi anni come chimico e abbia anche conseguito un dottorato di ricerca in una delle migliori università e pubblicato oltre 20 articoli, sono passato allo sviluppo web dopo che l\'ultima società di ingegneria per cui ho lavorato (fortemente focalizzata sulla chimica) ha chiuso i battenti nel 2011. Ho intrapreso questa transizione professionale per migliori opportunità di lavoro e di equilibrio tra lavoro e vita privata e, anni dopo, credo fermamente che questa sia stata la scelta corretta.<br /><br />&emsp;Sento di trovarmi in una posizione quasi unica in questo Ora posso utilizzare le mie capacità scientifiche e analitiche per sviluppare siti web (come il mio strumento di analisi CSS, <a href="https://cssburner.com" target="_blank" rel="noreferrer">CSSBurner</a>) che altre persone, o addirittura team, non sarebbero in grado di produrre in modo economicamente efficiente perché tali siti richiederebbero più personale con competenze diverse. <a href="https://www.asterank.com/kepler" target="_blank" rel="noreferrer">L\'API del progetto Kepler</a>, che interroga un database della NASA di oltre 2.000 esopianeti e oggetti non confermati di interesse, presenta una di queste opportunità. Questo database tenta mirabilmente di rendere i dati scientifici disponibili al pubblico. Tuttavia, la natura esoterica dei parametri API, aggiunti in un formato compatibile con Mongo DB, rende quasi impossibile l\'effettivo accesso pubblico. Kepler Stats è uno sforzo per visualizzare le statistiche del database del Progetto Kepler e integrare filtri a "valore aggiunto" - come un\'interfaccia utente facile da usare disponibile in più lingue - in modo che chiunque abbia abbastanza curiosità possa apprezzare più pienamente il valore dei preziosi dati del Progetto Kepler.'
  }
};

export default TEXT_MAP;
